# Generated by Django 5.2 on 2025-04-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Гдавное', 'verbose_name_plural': 'Главные'},
        ),
    ]
