# Generated by Django 5.2 on 2025-04-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_alter_main_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
