# Generated by Django 5.2 on 2025-04-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_alter_main_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='description2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
