# Generated by Django 5.2 on 2025-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_main_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more', models.CharField(max_length=200)),
                ('ambitious', models.CharField(max_length=100)),
                ('ambitious_description', models.TextField()),
                ('goal', models.CharField(max_length=100)),
                ('goal_description', models.TextField()),
                ('photo_about', models.ImageField(upload_to='media/', verbose_name='фото для о нас')),
                ('experts', models.CharField(verbose_name=150)),
                ('experts_description', models.TextField()),
                ('photo_experts', models.ImageField(upload_to='media/', verbose_name='фото для об экспертов')),
                ('participant_numbers', models.IntegerField()),
                ('awards_number', models.IntegerField(null=True)),
                ('projects', models.IntegerField(null=True)),
                ('reviews', models.IntegerField(null=True)),
                ('marketing', models.CharField(max_length=200)),
                ('marketing_strategy', models.CharField(verbose_name=50)),
                ('elements_of_marketing', models.CharField(verbose_name=250)),
                ('head_marketing', models.CharField(max_length=50)),
                ('head_marketing_description', models.CharField(max_length=150)),
                ('head_marketing_subdescription', models.CharField(max_length=200)),
                ('head_marketing_text', models.TextField()),
                ('evaluation_of_company', models.CharField(verbose_name=50)),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
