# Generated by Django 5.2 on 2025-04-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RemoveField(
            model_name='about',
            name='awards_number',
        ),
        migrations.RemoveField(
            model_name='about',
            name='elements_of_marketing',
        ),
        migrations.RemoveField(
            model_name='about',
            name='evaluation_of_company',
        ),
        migrations.RemoveField(
            model_name='about',
            name='experts',
        ),
        migrations.RemoveField(
            model_name='about',
            name='experts_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='head_marketing',
        ),
        migrations.RemoveField(
            model_name='about',
            name='head_marketing_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='head_marketing_subdescription',
        ),
        migrations.RemoveField(
            model_name='about',
            name='head_marketing_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='marketing',
        ),
        migrations.RemoveField(
            model_name='about',
            name='marketing_strategy',
        ),
        migrations.RemoveField(
            model_name='about',
            name='participant_numbers',
        ),
        migrations.RemoveField(
            model_name='about',
            name='photo_about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='photo_experts',
        ),
        migrations.RemoveField(
            model_name='about',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='about',
            name='reviews',
        ),
    ]
