# Generated by Django 5.2 on 2025-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_alter_about_options_remove_about_awards_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experts', models.CharField(verbose_name=150)),
                ('experts_description', models.TextField()),
                ('photo_experts', models.ImageField(upload_to='static/images/', verbose_name='фото для об экспертов')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_about', models.ImageField(upload_to='media/', verbose_name='фото для о нас')),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing', models.CharField(max_length=200)),
                ('marketing_strategy', models.CharField(verbose_name=50)),
                ('elements_of_marketing', models.CharField(verbose_name=250)),
                ('head_marketing', models.CharField(max_length=50)),
                ('head_marketing_description', models.CharField(max_length=150)),
                ('head_marketing_subdescription', models.CharField(max_length=200)),
                ('head_marketing_text', models.TextField()),
                ('evaluation_of_company', models.CharField(verbose_name=50)),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_numbers', models.IntegerField()),
                ('awards_number', models.IntegerField(null=True)),
                ('projects', models.IntegerField(null=True)),
                ('reviews', models.IntegerField(null=True)),
            ],
        ),
    ]
