# Generated by Django 5.2 on 2025-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_aboutexperts_aboutphoto_marketing_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutphoto',
            name='full_name',
            field=models.CharField(default='Имя по умолчанию', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutphoto',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
