# Generated by Django 5.2 on 2025-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_aboutphoto_full_name_aboutphoto_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
    ]
