# Generated by Django 5.2 on 2025-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0010_awardnumber_participantnumbers_projects_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardnumber',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantnumbers',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
