# Generated by Django 5.2 on 2025-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0012_picturemarketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_marketing', models.CharField(max_length=50)),
                ('head_marketing_description', models.CharField(max_length=150)),
                ('head_marketing_subdescription', models.CharField(max_length=200)),
                ('head_marketing_text', models.TextField()),
                ('evaluation_of_company', models.CharField(verbose_name=50)),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='MarketingHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_strategy', models.CharField(verbose_name=50)),
                ('elements_of_marketing', models.CharField(verbose_name=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Marketing',
        ),
    ]
