# Generated by Django 5.2 on 2025-04-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0013_helpmarketing_marketingbox_marketinghead_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingbox',
            options={'verbose_name': 'Маркетинг', 'verbose_name_plural': 'Маркетинг'},
        ),
    ]
