# Generated by Django 5.2 on 2025-04-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0015_reviewlist_reviewphrases_service_servicelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='icon_class',
            field=models.ImageField(upload_to='static/images/svg/'),
        ),
    ]
