# Generated by Django 5.2 on 2025-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0016_alter_servicelist_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='icon_class',
            field=models.TextField(),
        ),
    ]
