# Generated by Django 5.2 on 2025-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0017_alter_servicelist_icon_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingbox',
            options={'verbose_name': 'Маркетинг', 'verbose_name_plural': 'Маркетинги'},
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='icon_class',
            field=models.FileField(upload_to='icon_hw'),
        ),
    ]
