# Generated by Django 5.2 on 2025-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0018_alter_marketingbox_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='icon_class',
            field=models.FileField(blank=True, null=True, upload_to='icon_hw'),
        ),
    ]
