# Generated by Django 5.2 on 2025-04-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0019_alter_servicelist_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='picture_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='year_of_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/', verbose_name='фото для об фона'),
        ),
    ]
