# Generated by Django 5.2 on 2025-04-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0020_about_about_about_picture_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambitious', models.CharField(max_length=100)),
                ('ambitious_description', models.TextField()),
                ('goal', models.CharField(max_length=100)),
                ('goal_description', models.TextField()),
                ('picture_description', models.CharField(blank=True, max_length=150)),
                ('year_of_experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='ambitious',
        ),
        migrations.RemoveField(
            model_name='about',
            name='ambitious_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='about',
            name='goal_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='picture_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='year_of_experience',
        ),
    ]
