# Generated by Django 5.2 on 2025-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0021_aboutpro_remove_about_ambitious_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_description', models.CharField(blank=True, max_length=150)),
                ('year_of_experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpro',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='aboutpro',
            name='goal_description',
        ),
        migrations.RemoveField(
            model_name='aboutpro',
            name='picture_description',
        ),
        migrations.RemoveField(
            model_name='aboutpro',
            name='year_of_experience',
        ),
    ]
