# Generated by Django 5.2 on 2025-04-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0022_aboutprophoto_remove_aboutpro_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpro',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/about/', verbose_name='фото для об фона'),
        ),
    ]
