# Generated by Django 5.2 on 2025-04-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0023_aboutpro_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpro',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/', verbose_name='фото для об фона'),
        ),
    ]
