# Generated by Django 5.2 on 2025-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0024_alter_aboutpro_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutprophoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/', verbose_name='фото для об фона'),
        ),
    ]
