# Generated by Django 5.2 on 2025-04-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0025_aboutprophoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutphoto',
            old_name='full_name',
            new_name='about_about',
        ),
        migrations.RenameField(
            model_name='aboutphoto',
            old_name='position',
            new_name='about_experts_description',
        ),
        migrations.RemoveField(
            model_name='aboutphoto',
            name='photo_about',
        ),
        migrations.AddField(
            model_name='aboutphoto',
            name='about_experts',
            field=models.CharField(default='Имя по умолчанию', max_length=100),
        ),
    ]
