# Generated by Django 5.2 on 2025-04-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0026_rename_full_name_aboutphoto_about_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutphoto',
            name='about_experts_description',
            field=models.TextField(),
        ),
    ]
