# Generated by Django 5.2 on 2025-04-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0027_alter_aboutphoto_about_experts_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('our_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_goods', models.ImageField(upload_to='static/images/', verbose_name='фото сотрудника')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='адрес')),
                ('about_you', models.TextField(verbose_name='О вас')),
            ],
        ),
        migrations.DeleteModel(
            name='AwardNumber',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
