# Generated by Django 5.2 on 2025-04-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0028_goods_goodspicture_registartion_delete_awardnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_blog', models.ImageField(upload_to='static/images/', verbose_name='фото сотрудника')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('blog_description', models.TextField()),
            ],
        ),
    ]
