# Generated by Django 5.2 on 2025-04-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0029_blog_blogpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_icon', models.ImageField(upload_to='static/images/', verbose_name='фото сотрудника')),
                ('title', models.CharField(max_length=100)),
                ('more', models.CharField(max_length=100)),
                ('contact_address', models.CharField(max_length=100)),
            ],
        ),
    ]
