# Generated by Django 5.2 on 2025-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0030_adresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresses',
            name='photo_icon',
        ),
        migrations.AddField(
            model_name='adresses',
            name='icon_class',
            field=models.FileField(blank=True, null=True, upload_to='icon_hw'),
        ),
    ]
