# Generated by Django 5.2 on 2025-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0031_remove_adresses_photo_icon_adresses_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='static/images/', verbose_name='фото для фона')),
            ],
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Главное', 'verbose_name_plural': 'Главные'},
        ),
    ]
