# Generated by Django 5.2 on 2025-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0032_navigbar_alter_main_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigbar',
            name='photo',
        ),
        migrations.AddField(
            model_name='navigbar',
            name='icon_class',
            field=models.FileField(blank=True, null=True, upload_to='icon_hw'),
        ),
    ]
