# Generated by Django 5.2 on 2025-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0033_remove_navigbar_photo_navigbar_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigbar',
            name='icon_class',
            field=models.FileField(blank=True, null=True, upload_to='icon_hw/'),
        ),
    ]
